name: pr-test

on:
  pull_request:
    branches:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build optimized jar
        run: ./gradlew clean build optimizedJar